r=int(input())
t=int(input())
phi=22/7
volume=phi*(r*r)*t
luas=2*phi*r*(r+t)
keliling=2*phi*r
print("Volume = %.2f" %volume)
print("Luas = %.2f" %luas)
print("Keliling = %.2f\n" %keliling)
r1,t1=input().split()
r1=float(r1)
t1=float(t1)
phi1=22/7
volume1=phi1*(r1*r1)*t1
luas1=2*phi1*r1*(r1+t1)
keliling1=2*phi1*r1
print("Volume = %.2f" %volume1)
print("Luas = %.2f" %luas1)
print("Keliling = %.2f" %keliling1)