a,b,i,j,x,y=input().split()
a=float (a)
b=float (b)
i=float (i)
j=float (j)
x=float (x)
y=float (y)
H=(a-b)*(i/j)-(x+y)
print("%.3f\n" %H)
A1,B1=input().split()
I1,J1=input().split()
X1,Y1=input().split()
A1=float (A1)
B1=float (B1)
I1=float (I1)
J1=float (J1)
X1=float (X1)
Y1=float (Y1)
hasil1=(A1-B1)*(I1/J1)-(X1+Y1)
print("%.3f" %hasil1)